version: "3.6"
services:
  php70:
    build:
      context: php70
    container_name: php70
    ports:
      - "9000:9000"
    volumes:
      - ${CODE_PATH}:/var/www:rw
    stdin_open: true
    networks:
      - app-network
    tty: true
    privileged: true
    restart: always
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    networks:
      - app-network
    depends_on:
      - php70
    stdin_open: true
    tty: true
    privileged: true
    restart: always
    volumes:
      - ${CODE_PATH}:/var/www/html/:rw
      - ${NGINX_CONFIG}/conf/conf.d:/etc/nginx/conf.d:rw
      - ${NGINX_CONFIG}/conf/vhost:/etc/nginx/vhost:rw
      - ${NGINX_CONFIG}/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${NGINX_CONFIG}/logs/:/var/log/nginx/:rw
networks:
  app-network:
    driver: bridge