version: "3.6"
services:
  hyperf:
    build:
      context: hyperf
      args:
        PHP_VERSION: ${PHP_VERSION}
        SWOOLE_VERSION: ${SWOOLE_VERSION}
        PHPREDIS_VERSION: ${PHPREDIS_VERSION}
        COMPOSER_URL: ${COMPOSER_URL}
    container_name: hyperf
    ports:
      - "9700:9700"
    volumes:
      - ${CODE_PATH}:/var/www/html/:rw
    stdin_open: true
    networks:
      - app-network
    tty: true
    privileged: true
    restart: always
  php72:
    build:
      context: php
      args:
        PHP_VERSION: ${PHP_VERSION}
        SWOOLE_VERSION: ${SWOOLE_VERSION}
        PHPREDIS_VERSION: ${PHPREDIS_VERSION}
        COMPOSER_URL: ${COMPOSER_URL}
    container_name: php72
    ports:
      - "9800:9800"
    volumes:
      - ${CODE_PATH}:/var/www/html/:rw
    stdin_open: true
    networks:
      - app-network
    tty: true
    privileged: true
    restart: always
  nginx:
    image: nginx
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
      - "8899:8899"
    depends_on:
      - hyperf
      - php72
    networks:
      - app-network
    stdin_open: true
    tty: true
    privileged: true
    restart: always
    volumes:
      - ${CODE_PATH}:/var/www/html/:rw
      - ${NGINX_CONFIG}/conf/conf.d:/etc/nginx/conf.d:rw
      - ${NGINX_CONFIG}/conf/vhost:/etc/nginx/vhost:rw
      - ${NGINX_CONFIG}/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${NGINX_CONFIG}/logs/:/var/log/nginx/:rw
networks:
  app-network:
    driver: bridge