version: "3.6"
services:
  php73:
     build:
       context: hyperf
       args:
         PHP_VERSION: ${PHP_VERSION}
         SWOOLE_VERSION: ${SWOOLE_VERSION}
         PHPREDIS_VERSION: ${PHPREDIS_VERSION}
         COMPOSER_URL: ${COMPOSER_URL}
     container_name: php73
     ports:
       - "${PHP_PORT_9500}:9500"
     volumes:
       - ${CODE_PATH}:/var/www/hyperf-skeleton/:rw
     stdin_open: true
     networks:
       - app-network
     tty: true
     privileged: true
     restart: always

networks:
  app-network:
        driver: bridge