version: "3.6"
services:
  php73:
     build:
       context: hyperf
       args:
         PHP_VERSION: ${PHP_VERSION}
         SWOOLE_VERSION: ${SWOOLE_VERSION}
         PHPREDIS_VERSION: ${PHPREDIS_VERSION}
         COMPOSER_URL: ${COMPOSER_URL}
     container_name: php73
     ports:
       - "${PHP_PORT_9500}:9500"
     volumes:
       - ${CODE_PATH}hyperf-skeleton/:/var/www/hyperf-skeleton/:rw
       - ${CODE_PATH}:/var/www/html/:rw
     stdin_open: true
     networks:
       - app-network
     tty: true
     privileged: true
     restart: always
  php72:
    build:
      context: hyperf
      args:
        PHP_VERSION: ${PHP_VERSION}
        SWOOLE_VERSION: ${SWOOLE_VERSION}
        PHPREDIS_VERSION: ${PHPREDIS_VERSION}
        COMPOSER_URL: ${COMPOSER_URL}
    container_name: php72
    ports:
      - "${PHP_PORT_9000}:9000"
      - "9600:9600"
    volumes:
      - ${CODE_PATH}:/var/www/html/:rw
    stdin_open: true
    networks:
      - app-network
    tty: true
    privileged: true
    restart: always
  nginx:
     image: nginx
     ports:
       - "${NGINX_HTTP_HOST_PORT}:80"
       - "${NGINX_HTTPS_HOST_PORT}:443"
       - "8899:8899"
     depends_on:
       - php73
       - php72
     networks:
       - app-network
     stdin_open: true
     tty: true
     privileged: true
     restart: always
     volumes:
       - ${CODE_PATH}:/var/www/html/:rw
       - ${NGINX_CONFIG}/conf/conf.d:/etc/nginx/conf.d:rw
       - ${NGINX_CONFIG}/conf/vhost:/etc/nginx/vhost:rw
       - ${NGINX_CONFIG}/nginx.conf:/etc/nginx/nginx.conf:ro
       - ${NGINX_CONFIG}/logs/:/var/log/nginx/:rw
networks:
  app-network:
        driver: bridge